### ISSUE TITLE
Add option startRecord and maximumRecords

### ISSUE THREAD

**Issue by nichtich** [LibreCat/Catmandu-SRU#19]
Sometimes you don't want the full result set. This is somehow related to [Catmandu::Paged](https://metacpan.org/pod/Catmandu::Paged).

**Comment by cKlee** [comment]
@nichtich Why did you closes the issue? Your changes in the fork didn't make it to the source. Is there a reason for it? I find the changes quite helpful.

**Comment by nichtich** [comment]
I must confess I don't know anymore. There was some problem during implementation so I just gave up on this.

**Comment by nics** [comment]
I'm working on adding this

**Comment by nichtich** [comment]
Available in the `dev` branch, see #32
