### ISSUE TITLE
Why is Catmandu 1.20 needed to be able to run Catmandu::SRU

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu-SRU#42]
My builds on my projects start to fail complaining that Catmandu 1.10 can't be used with Catmandu::Identifier. I have some preformance reasons that for now I want to stick to Catmandu 1.10.

**Comment by nicolasfranck** [comment]
See also https://github.com/LibreCat/Catmandu-SRU/commit/930393427ec1f7d5c971dc109036b32a3cdf2079 that introduced this dependency.

**Comment by nics** [comment]
it's needed because it has a builder style fix
