### ISSUE TITLE
Add Catmandu::Store::SRU to allow counting?

### ISSUE THREAD

**Issue by nichtich** [LibreCat/Catmandu-SRU#46]
I tried to count the number of records in a result set without actually downloading all of them:

    catmandu count SRU --base http://sru.k10plus.de/opac-de-627 --query "pica.ddc=335.83092"

This does not work because the `count` command is only available for Stores, not for Importers. Shall we impement Catmandu::Store::SRU or is there another way? Catmandu::Store::SRU might also provide SRU Update protocol but I doubt that anyone actually needs this. I only want to count.

**Comment by nics** [comment]
I would prefer to add count to importers in general

**Comment by nichtich** [comment]
Ok, so there is no need to extend anything in Catmandu-SRU as the Importer already has method `count`. It only needs to be made available via the Catmandu CLI.

**Comment by nics** [comment]
yes i'll look into it

**Comment by nics** [comment]
Turns out this was already posssible with `catmandu convert SRU ... to Count`. Problem was that it iterated over the results to count. The just released Catmandu 1.2013 uses the count method when available.
